version: '2.2'
services:
  sqlite:
    image: nouchka/sqlite3
    volumes:
      - ./db:/run/db
    stdin_open: true
    tty: true
  web:
    image: nginx:latest
    links:
      - php
    depends_on:
      - php
  php:
    volumes:
      - ./db:/run/db
      - ./server:/var/www/html
