version: '2.2'
services:
  web:
    image: nginx:latest
    expose:
      - 80
    volumes:
      - ./server:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - php
    depends_on:
      - php
  php:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./db:/run/db
